const columns = [
  'Nome completo do solicitante',
  'Registrado por (e-mail)',
  'ID Chamado',
  'Email do solicitante (enduser)',
  'Período de abertura',
  'Período de fechamento',
  'Período Data Limite',
  'Chamados Ativos',
 'Vencido',
 'Reativado',
 'Registrado pelo usuário',
 'Status',
 'Clientes Disponíveis',
 'Incluir cliente relacionado',
 'VIP',
 'Login do solicitante (enduser)',
 'Site',
 'Localidade',
 'Localidade afetada',
 'Departamento Solicitante',
 'Solicitação (descrição)',
 'Detalhamento da solicitação',
 'Serviço',
 'Grupos Disponíveis',
 'Gerente',
 'Analista',
 'Tipo de serviço',
 'Tipo de change',
 'Competência',
 'Natureza',
 'Tópico',
 'Severidade',
 'Tipo de CI',
 'Resumo'
]
